# Generated by Django 6.0.3 on 2026-06-27 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Name should contain only alphabets.', regex='^[A-Za-z ]+$')])),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Name should contain only alphabets.', regex='^[A-Za-z ]+$')])),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
